name: Build

on:
  push:
  pull_request:

env:
  BUILD_DIR: 'out'
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emversion:
        - '3.1.59'
        - '3.1.60'
        - '3.1.73'

    steps:
    - uses: actions/checkout@v4
    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ matrix.emversion }}
        actions-cache-folder: ${{ env.EM_CACHE_FOLDER }}

    - uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build
      shell: bash
      run: |
        mkdir -p $BUILD_DIR
        emcc -sMODULARIZE=1 -sEXPORT_NAME=lib --js-library=./src/lib.js -v -o $BUILD_DIR/lib.js ./src/lib.c

    - name: List
      run: |
        ls -al .
        ls -al $BUILD_DIR

    - name: Test
      run: node ./index.js
      timeout-minutes: 1
